from docassemble.base.util import DAFile, DAFileCollection, DAFileList
from .al_document import ALDocument, ALDocumentBundle

__all__ = ["file_like"]

al_sessions_variables_to_remove = [
    # Internal fields
    '_internal',
    'nav',
    'url_args',
    'device_local',
    'allow_cron',
    'feedback_form',
    'github_repo_name',
    'github_user',
    'interview_short_title',
    'metadata_title',
    'multi_user',
    'session_local',
    'speak_text',
    'user_local',
    # Database-like fields we don't need to copy
    'all_courts',
    'macourts',
    'court_emails',    
    # AssemblyLine form-specific fields     
    'al_form_type',
    'al_version',    
    'form_approved_for_email_filing',    
    'interview_metadata',    
    'package_name',
    'package_version_number',
    'user_has_saved_answers',        
    # Variables that should be calculated fresh
    'signature_date',
    'al_court_bundle',
    'al_user_bundle',
    'case_name',
    'al_logo',    
    'AL_ORGANIZATION_HOMEPAGE',
    'AL_DEFAULT_STATE',
    'AL_DEFAULT_COUNTRY',
    'AL_DEFAULT_LANGUAGE',
    'AL_DEFAULT_OVERFLOW_MESSAGE',
    'AL_ORGANIZATION_TITLE',
    'about_this_interview_version_info',    
    # Variables from saving/loading state
    'al_formatted_sessions',
    'al_sessions_copy_success',
    'al_sessions_fast_forward_filtered_vars',
    'al_sessions_fast_forward_session',
    'al_sessions_filtered_vars',
    'al_sessions_launch_new_session',
    'al_sessions_list',
    'al_sessions_new_session_id',
    'al_sessions_preview_variables',
    'al_sessions_save_session_snapshot',
    'al_sessions_save_session_snapshot_success',
    'al_sessions_snapshot_label',
    'al_sessions_snapshot_results',
    'al_sessions_source_session',
    'al_sessions_variables_to_remove',
    'al_simple_filtered_vars',
    'filtered_vars_tmp',
    'simple_filtered_vars_tmp',
    'al_sessions_url_ask_snapshot',
    'al_sessions_url_ask_fast_forward',
    'al_sessions_variables_to_remove_from_new_interview',
    'file_like',
    # Some type annotations from Typing that seem plausible we'll use (not everything)
    'Any',
    'Callable',
    'Dict',
    'Generic',
    'Iterable',    
    'List',
    'Optional',
    'Set',
    'Tuple',
    'TypeVar',
    'Union',
    'Concatenate',
    'TypeLiteral',
    'ClassVar',
    'Final',
    'Annotated',
    'TypeGuard',
    'ParamSpec',
    'AnyStr',
    'Protocol',
    'NamedTuple',
    'NewType',
    'TypedDict',
    'FrozenSet',
    'DefaultDict',
    'OrderedDict',
    'ChainMap',
    'Counter',
    'Deque',
    'IO',
    'TextIO',
    'BinaryIO',
    'Pattern',
    'Match',
    'Text',
    # Variables that should always be created by code, so safe to recalculate
    'user_started_case',    
    'user_role',
]

al_sessions_variables_to_remove_from_new_interview = [
    'docket_number',
    'docket_numbers',
    'user_ask_role',
]

def file_like(obj):
    return isinstance(obj, DAFile) or isinstance(obj, DAFileCollection) or isinstance(obj, DAFileList) or isinstance(obj, ALDocument) or isinstance(obj, ALDocumentBundle)

